branches:
  only:
    - master

version: '1.0.{build}'

os: Visual Studio 2017

platform: Any CPU

configuration:
- Release

before_build:
- appveyor-retry dotnet restore "src\Gestaoaju.csproj"

build_script:
- dotnet build "src\Gestaoaju.csproj" -c %CONFIGURATION% --no-dependencies

before_test:
- appveyor-retry dotnet restore "test\Gestaoaju.Test.csproj"

test_script:
- dotnet test "test\Gestaoaju.Test.csproj" -c %CONFIGURATION%

cache:
- '%USERPROFILE%\.nuget\packages'
